# Generated by Django 4.2.30 on 2026-08-02 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('sos_event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='sos.sosevent')),
            ],
        ),
    ]
