# Generated by Django 4.2.30 on 2026-08-02 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SOSEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('location_url', models.URLField(blank=True)),
                ('video_room_name', models.CharField(blank=True, max_length=150)),
                ('video_room_url', models.URLField(blank=True)),
                ('voice_message', models.FileField(blank=True, null=True, upload_to='voice_messages/')),
                ('police_station_name', models.CharField(blank=True, max_length=255)),
                ('police_station_address', models.TextField(blank=True)),
                ('police_station_phone', models.CharField(blank=True, max_length=20)),
                ('sms_status', models.CharField(blank=True, default='pending', max_length=255)),
                ('video_status', models.CharField(blank=True, default='pending', max_length=50)),
                ('voice_status', models.CharField(blank=True, default='pending', max_length=50)),
                ('police_status', models.CharField(blank=True, default='pending', max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved'), ('false_alarm', 'False Alarm')], default='active', max_length=20)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sos_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='SOSEventContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('relationship', models.CharField(blank=True, max_length=100)),
                ('mobile_number', models.CharField(max_length=20)),
                ('sms_sent', models.BooleanField(default=False)),
                ('sms_error', models.CharField(blank=True, max_length=255)),
                ('sos_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notified_contacts', to='sos.sosevent')),
            ],
        ),
    ]
